### ISSUE TITLE
request for iTerm2 support for Mac OS X

### ISSUE THREAD

**Issue by The-Alchemist** [basti1302/startexplorer#62]
[iTerm2](http://iterm2.com/) is the preferred terminal for Mac OS X.  What would it take to add support for it?

I can submit a pull request if someone can point me to the right file(s) to edit. :)

**Comment by basti1302** [comment]
That would be https://github.com/basti1302/startexplorer/blob/master/plugin/src/de/bastiankrol/startexplorer/crossplatform/RuntimeExecCallsMacOs.java

**Comment by basti1302** [comment]
I'm not on MacOS so forgive my naïvety - I understand that iTerm2 is not installed out of the box but you have to install it separately. Just replacing `Terminal` with iTerm2 at https://github.com/basti1302/startexplorer/blob/master/plugin/src/de/bastiankrol/startexplorer/crossplatform/RuntimeExecCallsMacOs.java#L63 would break the plug-in for everyone who does not have iTerm2 installed, right? That's not good :-)

I think there are two options. You can create a [custom desktop environment configuration](http://basti1302.github.io/startexplorer/help/04_preferences.html#desktop_environment) for yourself with iTerm2 configured.

Or you could submit a pull request that adds an additional pre-configured desktop environment to the [DesktopEnvironment enum](https://github.com/basti1302/startexplorer/blob/master/plugin/src/de/bastiankrol/startexplorer/crossplatform/DesktopEnvironment.java) named, say, MAC_OS_WITH_ITERM_2("iTerm2") that the user can choose from.

If you have any means to detect whether iTerm2 is installed  at runtime then you could even extend the [DesktopEnvironmentAutoDetecter](https://github.com/basti1302/startexplorer/blob/master/plugin/src/de/bastiankrol/startexplorer/crossplatform/DesktopEnvironmentAutoDetecter.java#L39) to automatically choose MAC_OS_WITH_ITERM_2 if it is available and fall back to the current MAC_OS configuration if not.

**Comment by basti1302** [comment]
Closed due to inactivity. Feel free to provide a pull request if you are still interested.
