### ISSUE TITLE
Update site doesn't work with Eclipse Mars (Eclipse IDE v4.5.0)

### ISSUE THREAD

**Issue by andham** [basti1302/startexplorer#65]
Trying to install via the updatesite with newly released Eclipse Mars fails. It says:

No repository found at http://basti1302.github.com/startexplorer/update/.

**Comment by paulvi** [comment]
Try again, every day hundreds people install.
That maybe was Github.io outage

**Comment by andham** [comment]
It turns out that this issue depends on the corporate web proxy. The problem only seems to affects update sites on github though. I'm guessing there's some redirect happening, or possibly some blocking in the proxy filter. Not your problem in any case.

**Comment by basti1302** [comment]
:+1:
