### ISSUE TITLE
Use HTTPS for update site

### ISSUE THREAD

**Issue by rob-X1** [basti1302/startexplorer#69]
GitHub provides HTTPS access to the web resources - hence the update site can be accessed via HTTPS without any changes.

Therefore I recommend to change all occurrences of the Update site URL to

https://basti1302.github.io/startexplorer/update/

**Comment by basti1302** [comment]
Nice catch. Done.

**Comment by rob-X1** [comment]
The [web page of StartExplorer](http://basti1302.github.io/startexplorer/) again states that the Update site is on HTTP not HTTPS:

The URL http://basti1302.github.com/startexplorer/update/ is used two times on this page.
