### ISSUE TITLE
i cannot see the icon in the tool bar 

### ISSUE THREAD

**Issue by vipzrx** [basti1302/startexplorer#70]
![20151221_160002](https://cloud.githubusercontent.com/assets/5094958/11926006/ec037466-a7fb-11e5-88c0-0506f7a8dfed.png)

![20151221_160054](https://cloud.githubusercontent.com/assets/5094958/11926018/0b8b9bf6-a7fc-11e5-810d-2d7e80fc3e39.png)

**Comment by basti1302** [comment]
StartExplorer does not add an icon to the toolbar. It adds an item to the context menu. Right click on a file or a directory in the project explorer, then you should see an icon in the context menu that pops up.
